<a href="https://colab.research.google.com/github/unnati2612/aiml-30-days/blob/main/Day2_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [4]:
arr.shape


(5,)

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.mean()

np.float64(30.0)

In [8]:
arr.max()

np.int64(50)

In [9]:
arr.min()

np.int64(10)

In [10]:
arr + 5

array([15, 25, 35, 45, 55])

In [11]:
arr*5

array([ 50, 100, 150, 200, 250])

In [16]:
matrix = np.array([
    [5,10,15,16],
    [25,30,35,36],
    [45,50,55,56]
])

matrix

array([[ 5, 10, 15, 16],
       [25, 30, 35, 36],
       [45, 50, 55, 56]])

In [17]:
matrix.shape

(3, 4)

In [18]:
matrix[0]

array([ 5, 10, 15, 16])

In [19]:
matrix[:,1]

array([10, 30, 50])

In [20]:
matrix[1,2]

np.int64(35)

# Day 2 – NumPy Basics

## What is NumPy?
NumPy is a Python library used for numerical computations.
It provides arrays which are faster and more efficient than Python lists.

## Key Learnings
- Created 1D and 2D arrays
- Understood shape and data types
- Performed mathematical operations
- Practiced indexing and slicing

## Why NumPy is important for ML?
Machine Learning models work on numerical data.
NumPy arrays are used internally by ML libraries like Scikit-learn and PyTorch.
