<a href="https://colab.research.google.com/github/unnati2612/aiml-30-days/blob/main/Day4_Logistic_regressionPass_fail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
data = {
    "marks" : [1,2,3,4,5,6,7,8],
    "result" :[0,0,0,0,1,1,1,1]
}

#0=fail, 1=pass

df = pd.DataFrame(data)
df

marks  result
0      1       0
1      2       0
2      3       0
3      4       0
4      5       1
5      6       1
6      7       1
7      8       1

In [6]:
X = df[["marks"]]
y = df["result"]

In [8]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2, random_state = 42
)

In [13]:
train_test_split(
    X,y,test_size=0.2, random_state = 42
)

[   marks
 0      1
 7      8
 2      3
 4      5
 3      4
 6      7,
    marks
 1      2
 5      6,
 0    0
 7    1
 2    0
 4    1
 3    0
 6    1
 Name: result, dtype: int64,
 1    0
 5    1
 Name: result, dtype: int64]

In [10]:
model= LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [12]:
y_predict = model.predict(X_test)
y_predict

array([0, 1])

In [14]:
accuracy = accuracy_score(y_test,y_predict)
accuracy

1.0

In [16]:
cm = confusion_matrix(y_test,y_predict)
cm

array([[1, 0],
       [0, 1]])

In [19]:
mark = np.array([[3.5]])
model.predict(mark)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

# Day 4 – Logistic Regression (Classification)

## Problem
Predict whether a student will pass or fail based on marks.

## Model
Logistic Regression (Classification model)

## Steps
- Created dataset
- Selected feature and target
- Split data into train and test
- Trained Logistic Regression model
- Made predictions
- Evaluated using accuracy and confusion matrix

## Learning
This project helped me understand classification problems
where output is categorical (Pass / Fail).


🎯 Use cases

Pass / Fail

Spam detection

Disease present or not

Loan approve / rejec